services:
  db:
    image: postgres:15-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - '6379:6379'
    command: redisEventBus-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api:
    build:
      context: ./
    depends_on:
      - db
      - cache
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      CONNECTION_STRING:  host=localhost port=5432 user=postgres dbname=labraboard password=postgres
    links:
      - db
      - cache
  handlers:
    command: ./handlers
    build:
      context: ./
    depends_on:
      - db
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      CONNECTION_STRING:  host=localhost port=5432 user=postgres dbname=labraboard password=postgres
    links:
      - db
      - cache
volumes:
  db:
    driver: local
  cache:
    driver: local