{{- if not (empty (.Values.secretData)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "labraboard.fullname" . }}
  labels:
    {{- include "labraboard.labels" . | nindent 4 }}
stringData:
  {{- .Values.secretData | toYaml | nindent 2 }}
{{- end -}}