definitions:
  dtos.AddEnvDto:
    properties:
      isSecret:
        type: boolean
      name:
        type: string
      value:
        type: string
    type: object
  dtos.AddVariableDto:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  dtos.CreateProjectDto:
    properties:
      'repositoryBranch:':
        type: string
      repositoryTerraformPath:
        type: string
      repositoryUrl:
        type: string
      type:
        type: integer
    type: object
  dtos.GetProjectBaseDto:
    properties:
      id:
        type: string
      type:
        type: integer
    type: object
  dtos.GetProjectDto:
    properties:
      envs:
        additionalProperties:
          type: string
        type: object
      id:
        type: string
      'repositoryBranch:':
        type: string
      repositoryTerraformPath:
        type: string
      repositoryUrl:
        type: string
      type:
        type: integer
      variables:
        additionalProperties:
          type: string
        type: object
    type: object
  dtos.PlanDto:
    properties:
      createdOn:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
  dtos.PlanWithOutputDto:
    properties:
      createdOn:
        type: string
      id:
        type: string
      outputs: {}
      status:
        type: string
    type: object
  dtos.SchedulePlan:
    properties:
      when:
        type: string
    type: object
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /project:
    get:
      consumes:
      - application/json
      description: projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.GetProjectBaseDto'
            type: array
      summary: Get all projects
      tags:
      - project
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Create project
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateProjectDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a new project
      tags:
      - project
  /project/{projectId}:
    get:
      consumes:
      - application/json
      description: Fetch a project by id
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetProjectDto'
      summary: Fetch a project by id
      tags:
      - project
  /project/{projectId}/env:
    put:
      consumes:
      - application/json
      description: Add new env to a project
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: Env to add
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dtos.AddEnvDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Add new env to a project
      tags:
      - project
  /project/{projectId}/env/{envName}:
    delete:
      consumes:
      - application/json
      description: Remove new env to a project
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: env name
        in: path
        name: envName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Remove new env to a project
      tags:
      - project
  /project/{projectId}/variable:
    put:
      consumes:
      - application/json
      description: Add new variable to a project
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: Env to add
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dtos.AddVariableDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Add new variable to a project
      tags:
      - project
  /project/{projectId}/variable/{variableName}:
    delete:
      consumes:
      - application/json
      description: Remove new variable to a project
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: variable name
        in: path
        name: variableName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Remove new variable to a project
      tags:
      - project
  /state/terraform/{projectId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get terraform state for a given project
      tags:
      - state
    post:
      consumes:
      - application/json
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Update terraform state for a given project
      tags:
      - state
  /terraform/{projectId}/plan:
    get:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.PlanDto'
            type: array
      summary: Fetch all the terraform plans for a given project
      tags:
      - terraform
    post:
      consumes:
      - application/json
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Method to run Terraform Plan for a given project and return the plan
        id
      tags:
      - terraform
  /terraform/{projectId}/plan/{planId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: plan id
        in: path
        name: planId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.PlanWithOutputDto'
      summary: Method returns the terraform plan output for a given plan id
      tags:
      - terraform
  /terraform/{projectId}/plan/{planId}/apply:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: plan id
        in: path
        name: planId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Method Apply changes for a given plan id return deployment id
      tags:
      - terraform
  /terraform/{projectId}/plan/{planId}/apply/{deploymentId}:
    get:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: plan id
        in: path
        name: planId
        required: true
        type: string
      - description: deployment id
        in: path
        name: deploymentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Method to fetch deployment status for a given deployment id
      tags:
      - terraform
  /terraform/{projectId}/plan/{planId}/schedule:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: project id
        in: path
        name: projectId
        required: true
        type: string
      - description: plan id
        in: path
        name: planId
        required: true
        type: string
      - description: Schedule plan
        in: body
        name: schedulePlan
        required: true
        schema:
          $ref: '#/definitions/dtos.SchedulePlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.PlanDto'
            type: array
      summary: Fetch all the terraform plans for a given project
      tags:
      - terraform
swagger: "2.0"
